spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/base
    username: base
    password: base
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
